apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windows-bios-installer
resources:
  - namespace.yaml
  - ../../base
  - windows-bios-installer-configmaps.yaml
  - windows-bios-installer-pipeline.yaml
  #- windows10-installer-pipelinerun.yaml