apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httpd-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: httpd-sevice-account
    namespace: httpd-server
roleRef:
  kind: ClusterRole
  name: httpd-clusterrole
  apiGroup: rbac.authorization.k8s.io