apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: httpd-scc
  namespace: httpd-server
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
allowedCapabilities: []
allowedUnsafeSysctls:
  - "*"
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1001079999
seccompProfiles:
  - runtime/default
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:httpd-server:httpd-sevice-account