apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microshift-instance
resources:
  - namespace.yaml
  - ../../base
  - microshift-instance-pipeline.yaml
  - microshift-cleanup-pipeline.yaml
  #- microshift-instance-pipelinerun.yaml