apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: microshift-instance-wip
  namespace: microshift-instance
spec:
  tasks:
    - name: generate-ssh-keys
      params:
        - name: privateKeyConnectionOptions
          value:
            - 'user:microshift'
            - 'disable-strict-host-key-checking:true'
      taskRef:
        kind: Task
        name: generate-ssh-keys
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |-
        - name: activation-key
          value: $(params.activation-key)
        - name: org
          value: $(params.org)
        - name: activation-key
          value: $(params.activation-key)
        - name: org
          value: $(params.org)
        - name: activation-key
          value: $(params.activation-key)
        - name: org
          value: $(params.org)
        - name: activation-key
          value: $(params.activation-key)
        - name: org
          value: $(params.org)
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: microshift-vm-
              annotation:
                description: Fedora VM generated by microshift-instance pipeline
              labels:
                app: microshift-vm
                vm.kubevirt.io/template.revision: '1'
                vm.kubevirt.io/template.version: v0.29.1
            spec:
              dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  creationTimestamp: null
                  name: rhel9-microshift
                spec:
                  sourceRef:
                    kind: DataSource
                    name: rhel9
                    namespace: openshift-virtualization-os-images
                  storage:
                    resources:
                      requests:
                        storage: 30Gi
              running: true
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: microshift-vm
                spec:
                  accessCredentials:
                    - sshPublicKey:
                        source:
                          secret:
                            secretName: $(tasks.generate-ssh-keys.results.publicKeySecretName)
                        propagationMethod:
                          configDrive: {}
                  domain:
                    cpu:
                      cores: 2
                      sockets: 1
                      threads: 1
                    devices:
                      disks:
                        - name: rootdisk
                          bootOrder: 1
                          disk:
                            bus: virtio
                        - name: cloudinitdrive
                          disk:
                            bus: virtio
                      interfaces:
                        - bridge: {}
                          name: default
                      networkInterfaceMultiqueue: true
                      rng: {}
                    resources:
                      requests:
                        memory: 4Gi
                  hostname: microshift-vm
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - dataVolume:
                        name: rhel9-microshift
                      name: rootdisk
                    - name: cloudinitdrive
                      cloudInitConfigDrive:
                        userData: |
                          #cloud-config
                          user: microshift
                          password: r3dh@t2024
                          chpasswd: { expire: False }
                          rh_subscription:
                            activation-key: $(params.activation-key)
                            org: $(params.org)
                          packages:
                            - dnf-automatic
                          runcmd:
                            - systemctl enable --now dnf-automatic-install.timer
                          rh_subscription:
                            activation-key: $(params.activation-key)
                            org: $(params.org)
                          packages:
                            - dnf-automatic
                          runcmd:
                            - systemctl enable --now dnf-automatic-install.timer
      runAfter:
        - generate-ssh-keys
      taskRef:
        kind: Task
        name: create-vm-from-manifest
    - name: execute-in-vm
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: secretName
          value: $(tasks.generate-ssh-keys.results.privateKeySecretName)
        - name: script
          value: |
            sudo subscription-manager refresh
            sudo subscription-manager attach --auto
            sudo subscription-manager repos \
              --enable rhocp-4.16-for-rhel-9-$(uname -m)-rpms \
              --enable fast-datapath-for-rhel-9-$(uname -m)-rpms
            sudo dnf install -y microshift
      runAfter:
        - create-vm-from-manifest
      taskRef:
        kind: Task
        name: execute-in-vm
