kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-server
  namespace: httpd-server
  labels:
    app: httpd-server
    app.kubernetes.io/component: httpd-server
    app.kubernetes.io/instance: httpd-server
    app.kubernetes.io/name: httpd-server
    app.kubernetes.io/part-of: httpd-server
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-ubi9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-server
        deployment: httpd-server
    spec:
      volumes:
        - name: httpd-data-volume
          persistentVolumeClaim:
            claimName: httpd-data-pvc
      containers:
        - name: httpd-server
          image: >-
            image-registry.openshift-image-registry.svc:5000/httpd-server/httpd-server:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: httpd-data-volume
              mountPath: /opt/app-root/src
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600