---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fedora-cleanup
spec:
  tasks:
    - name: cleanup-vm
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
      taskRef:
        kind: Task
        name: cleanup-vm
    - name: delete-data-object
      params:
        - name: name
          value: $(tasks.modify-data-object.results.name)
      runAfter:
        - cleanup-vm
      taskRef:
        kind: Task
        name: delete-data-object
