---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: fedora-example-run-
  namespace: openshift-cnv
spec:
  pipelineRef:
    name: fedora-example
  taskRunSpecs:
    - pipelineTaskName: modify-data-object
      taskServiceAccountName: modify-data-object-task
    - pipelineTaskName: generate-ssh-keys
      taskServiceAccountName: generate-ssh-keys-task
    - pipelineTaskName: create-vm-from-manifest
      taskServiceAccountName: create-vm-from-manifest-task
    - pipelineTaskName: execute-in-vm
      taskServiceAccountName: execute-in-vm-task