apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fedora-example
resources:
  - namespace.yaml
  - ../../base
  - fedora-example-pipeline.yaml
  - fedora-cleanup-pipeline.yaml
  #- fedora-example-pipelinerun.yaml