apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fedora-example
resources:
  - namespace.yaml
  - ../../base
  - server-deployer-pipeline.yaml
  #- server-deployer-pipelinerun.yaml