apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama-langchain
resources:
  - namespace.yaml
  - ../../base
  - ollama-langchain-pipeline.yaml
  #- ollama-langchain-pipelinerun.yaml